In [1]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 200)

In [2]:
df = pd.read_csv('nba_player_averages_2026.csv')
df.head()

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season
0,A.J. Lawson,TOR,25.0,24,9.4,1.4,3.3,0.436,0.8,1.9,0.422,0.6,0.8,0.778,0.4,1.4,1.8,0.3,0.3,0.5,0.2,1.1,4.2,2026
1,AJ Green,MIL,26.0,78,29.1,3.4,7.9,0.424,3.0,7.1,0.419,0.7,0.8,0.855,0.4,2.4,2.7,1.9,1.0,0.5,0.1,2.3,10.4,2026
2,AJ Johnson,DAL,21.0,48,9.4,1.2,3.7,0.324,0.3,1.2,0.211,0.7,0.8,0.850,0.3,0.9,1.1,1.0,0.6,0.2,0.1,0.6,3.3,2026
3,Aaron Gordon,DEN,30.0,36,27.9,5.5,11.1,0.497,1.7,4.4,0.389,3.5,4.5,0.767,1.4,4.4,5.8,2.7,1.1,0.6,0.3,1.7,16.2,2026
4,Aaron Holiday,HOU,29.0,57,13.7,1.8,4.4,0.417,1.2,3.0,0.394,0.6,0.7,0.854,0.2,0.8,1.0,1.1,0.7,0.5,0.1,1.3,5.5,2026

In [3]:
df[df['Player'].isin(['Cade Cunningham', 'Jalen Johnson', 'Jayson Tatum'])]

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season
71,Cade Cunningham,DET,24.0,64,33.9,8.6,18.6,0.461,2.0,5.7,0.342,4.8,6.0,0.812,0.9,4.7,5.5,9.9,3.7,1.4,0.8,3.1,23.9,2026
234,Jalen Johnson,ATL,24.0,72,35.2,8.3,17.1,0.489,1.7,4.7,0.352,4.2,5.3,0.788,1.4,8.9,10.3,7.9,3.4,1.2,0.4,2.1,22.5,2026
266,Jayson Tatum,BOS,28.0,16,32.6,7.4,17.9,0.411,2.9,8.9,0.329,4.1,4.9,0.823,0.5,9.5,10.0,5.3,2.4,1.4,0.2,1.6,21.8,2026

In [4]:
px.histogram(df, x='PTS', nbins=10, title='Distribution of Points per Game', labels={'PTS': 'Points per Game'})

In [5]:
fig = make_subplots(rows=1, cols=2, subplot_titles=('Points vs Field Goal Percentage', 'Points vs Free Throw Percentage'))

fig.add_trace(
    go.Scatter(x=df['PTS'], y=df['FG%'], mode='markers', text=df['Player'], name='Field Goal %'),
    row=1, col=1
)

fig.add_trace(
    go.Scatter(x=df['PTS'], y=df['FT%'], mode='markers', text=df['Player'], name='Free Throw %'),
    row=1, col=2
)

fig.update_layout(title='Points vs Shooting Percentages')

fig.show()

In [6]:
adp_df = pd.read_csv('adp_2026_27.csv')
adp_df.head()

   ESPN_ADP_Rank                   Player Team Positions
0              1             Nikola Jokic  DEN         C
1              2  Shai Gilgeous-Alexander  OKC        PG
2              3        Victor Wembanyama  SAS         C
3              4              Luka Doncic  LAL     PG,SG
4              5    Giannis Antetokounmpo  MIA      PF,C

In [7]:
df = df.merge(adp_df, on=['Player', 'Team'], how='left')
df.rename(columns={'ESPN_ADP_Rank': 'ADP'}, inplace=True)
df.head()

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
0,A.J. Lawson,TOR,25.0,24,9.4,1.4,3.3,0.436,0.8,1.9,0.422,0.6,0.8,0.778,0.4,1.4,1.8,0.3,0.3,0.5,0.2,1.1,4.2,2026,NaN,NaN
1,AJ Green,MIL,26.0,78,29.1,3.4,7.9,0.424,3.0,7.1,0.419,0.7,0.8,0.855,0.4,2.4,2.7,1.9,1.0,0.5,0.1,2.3,10.4,2026,NaN,NaN
2,AJ Johnson,DAL,21.0,48,9.4,1.2,3.7,0.324,0.3,1.2,0.211,0.7,0.8,0.850,0.3,0.9,1.1,1.0,0.6,0.2,0.1,0.6,3.3,2026,NaN,NaN
3,Aaron Gordon,DEN,30.0,36,27.9,5.5,11.1,0.497,1.7,4.4,0.389,3.5,4.5,0.767,1.4,4.4,5.8,2.7,1.1,0.6,0.3,1.7,16.2,2026,113.0,"PF,C"
4,Aaron Holiday,HOU,29.0,57,13.7,1.8,4.4,0.417,1.2,3.0,0.394,0.6,0.7,0.854,0.2,0.8,1.0,1.1,0.7,0.5,0.1,1.3,5.5,2026,NaN,NaN

In [8]:
df.sort_values(by='ADP', inplace=True)

In [21]:
df.head(200)

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
501,Shai Gilgeous-Alexander,OKC,27.0,68,33.2,10.8,19.4,0.553,1.7,4.4,0.386,7.9,9.0,0.879,0.6,3.7,4.3,6.6,2.2,1.4,0.8,2.0,31.1,2026,2.0,PG
559,Victor Wembanyama,SAS,22.0,64,29.2,8.6,16.9,0.512,1.9,5.5,0.349,5.8,7.0,0.827,2.0,9.5,11.5,3.1,2.4,1.0,3.1,2.4,25.0,2026,3.0,C
31,Anthony Edwards,MIN,24.0,61,35.0,9.9,20.2,0.489,3.4,8.4,0.399,5.7,7.2,0.796,0.6,4.4,5.0,3.7,2.9,1.4,0.8,1.9,28.8,2026,6.0,"PG,SF,SG"
71,Cade Cunningham,DET,24.0,64,33.9,8.6,18.6,0.461,2.0,5.7,0.342,4.8,6.0,0.812,0.9,4.7,5.5,9.9,3.7,1.4,0.8,3.1,23.9,2026,7.0,"PG,SG"
266,Jayson Tatum,BOS,28.0,16,32.6,7.4,17.9,0.411,2.9,8.9,0.329,4.1,4.9,0.823,0.5,9.5,10.0,5.3,2.4,1.4,0.2,1.6,21.8,2026,8.0,"SF,PF"
30,Anthony Davis,WAS,33.0,20,31.3,8.5,16.7,0.506,0.5,1.9,0.270,3.0,4.1,0.728,3.1,8.0,11.1,2.8,2.1,1.1,1.7,2.1,20.4,2026,9.0,"PF,C"
317,Karl-Anthony Towns,NYK,30.0,75,31.0,6.9,13.8,0.501,1.5,4.1,0.368,4.8,5.5,0.858,3.1,8.7,11.9,3.0,2.5,0.9,0.5,3.4,20.1,2026,11.0,"PF,C"
245,James Harden,CLE,36.0,70,34.8,7.0,16.0,0.434,3.1,8.2,0.375,6.6,7.5,0.884,0.6,4.2,4.8,8.0,3.5,1.1,0.4,2.0,23.6,2026,12.0,"PG,SG"
554,Tyrese Maxey,PHI,25.0,70,38.0,9.9,21.4,0.462,3.1,8.6,0.367,5.3,6.0,0.892,0.3,3.8,4.1,6.6,2.4,1.9,0.8,2.2,28.3,2026,13.0,"PG,SG"
151,Domantas Sabonis,SAC,30.0,19,29.7,6.3,11.6,0.543,0.3,1.4,0.185,2.9,4.1,0.727,3.4,8.0,11.4,4.1,2.7,0.9,0.2,3.5,15.8,2026,15.0,"C,PF"
21,Amen Thompson,HOU,23.0,79,37.4,7.1,13.2,0.534,0.3,1.5,0.216,3.8,4.9,0.779,3.0,4.8,7.8,5.3,2.4,1.5,0.6,2.2,18.3,2026,16.0,"PG,SF,SG"
509,Stephen Curry,GSW,38.0,43,30.9,8.7,18.6,0.468,4.4,11.3,0.393,4.7,5.1,0.923,0.4,3.2,3.6,4.7,2.8,1.1,0.4,1.7,26.6,2026,18.0,PG
231,Jalen Brunson,NYK,29.0,74,35.0,9.3,19.9,0.467,2.6,7.1,0.369,4.8,5.7,0.841,0.4,2.9,3.3,6.8,2.4,0.8,0.1,2.3,26.0,2026,19.0,PG
531,Trae Young,WAS,27.0,15,25.6,5.4,11.8,0.458,1.8,5.3,0.338,5.3,6.5,0.825,0.3,1.7,2.0,8.0,2.6,0.9,0.1,2.2,17.9,2026,20.0,PG
154,Donovan Mitchell,CLE,29.0,70,33.5,9.7,20.0,0.483,3.2,8.8,0.364,5.3,6.1,0.865,0.7,3.8,4.5,5.7,2.8,1.5,0.3,2.3,27.9,2026,21.0,"PG,SG"
455,Pascal Siakam,IND,32.0,62,33.2,9.0,18.6,0.484,1.7,4.7,0.358,4.2,6.1,0.693,1.4,5.2,6.6,3.8,2.2,1.1,0.4,2.4,24.0,2026,22.0,"C,PF,SF"
107,Cooper Flagg,DAL,19.0,70,33.5,8.0,17.1,0.468,1.0,3.5,0.295,4.0,4.9,0.827,1.2,5.4,6.7,4.5,2.3,1.2,0.9,2.0,21.0,2026,23.0,"PF,SF,SG"
333,Kevin Durant,HOU,37.0,78,36.4,9.2,17.6,0.520,2.4,5.8,0.413,5.2,6.0,0.874,0.5,4.9,5.5,4.8,3.2,0.8,0.9,1.8,26.0,2026,24.0,"PF,SF,SG"
496,Scottie Barnes,TOR,24.0,80,33.5,7.1,14.0,0.507,0.9,2.8,0.304,3.0,3.7,0.815,1.9,5.6,7.5,5.9,2.6,1.4,1.5,2.6,18.1,2026,25.0,"C,PF,SF,SG"
39,Bam Adebayo,MIA,28.0,73,32.4,6.9,15.7,0.442,1.7,5.5,0.318,4.5,5.8,0.778,2.0,8.0,10.0,3.2,1.6,1.2,0.7,1.7,20.1,2026,26.0,"C,PF"
299,Josh Giddey,CHI,23.0,54,32.1,5.9,13.3,0.448,1.9,5.2,0.364,3.2,4.2,0.763,1.2,7.1,8.3,9.1,3.6,1.0,0.5,1.7,17.0,2026,27.0,"PG,SG,SF"
239,Jalen Williams,OKC,25.0,33,28.4,6.5,13.5,0.484,0.7,2.3,0.299,3.3,3.9,0.837,0.8,3.8,4.6,5.5,1.9,1.2,0.3,2.0,17.1,2026,28.0,"PF,SF,SG"
19,Alperen Sengun,HOU,23.0,72,33.3,8.1,15.6,0.519,0.6,1.8,0.305,3.6,5.2,0.691,3.0,5.9,8.9,6.2,3.2,1.2,1.1,3.3,20.4,2026,30.0,"C,PF"
177,Evan Mobley,CLE,25.0,65,31.9,7.2,13.2,0.546,1.0,3.2,0.297,2.8,4.6,0.606,2.4,6.6,9.0,3.6,1.9,0.7,1.7,2.4,18.2,2026,31.0,"PF,C"
234,Jalen Johnson,ATL,24.0,72,35.2,8.3,17.1,0.489,1.7,4.7,0.352,4.2,5.3,0.788,1.4,8.9,10.3,7.9,3.4,1.2,0.4,2.1,22.5,2026,32.0,"PF,SF"
242,Jamal Murray,DEN,29.0,75,35.4,8.8,18.1,0.483,3.3,7.5,0.435,4.6,5.2,0.887,0.4,4.0,4.4,7.1,2.3,0.9,0.4,1.7,25.4,2026,33.0,PG
454,Paolo Banchero,ORL,23.0,72,34.7,7.3,16.0,0.459,1.2,3.8,0.305,6.3,8.2,0.775,1.2,7.2,8.4,5.2,3.1,0.7,0.6,2.0,22.2,2026,34.0,"PF,SF"
214,Ivica Zubac,IND,29.0,48,30.1,6.0,10.0,0.598,0.0,0.0,0.000,2.1,3.0,0.711,3.4,7.2,10.6,2.2,1.8,0.4,0.8,2.3,14.1,2026,35.0,C
130,De'Aaron Fox,SAS,28.0,72,31.0,7.1,14.5,0.486,1.8,5.5,0.332,2.6,3.4,0.760,0.6,3.2,3.8,6.2,2.3,1.2,0.3,2.3,18.6,2026,36.0,"PG,SG"
88,Chet Holmgren,OKC,24.0,69,28.9,6.3,11.3,0.557,1.3,3.5,0.362,3.3,4.1,0.792,1.9,7.0,8.9,1.7,1.6,0.6,1.9,2.3,17.1,2026,38.0,"PF,C"
145,Desmond Bane,ORL,28.0,82,33.6,7.1,14.7,0.484,2.0,5.2,0.391,3.8,4.2,0.908,1.2,2.9,4.1,4.1,2.0,1.0,0.5,3.1,20.1,2026,41.0,"SG,SF"
178,Franz Wagner,ORL,24.0,34,30.0,7.2,14.9,0.481,1.4,4.1,0.345,4.8,5.8,0.823,1.3,3.9,5.2,3.3,1.7,0.9,0.3,2.1,20.6,2026,43.0,"PF,SF"
279,Joel Embiid,PHI,32.0,38,31.6,9.0,18.3,0.489,1.4,4.2,0.333,7.5,8.8,0.854,2.0,5.7,7.7,3.9,2.9,0.6,1.2,2.2,26.9,2026,45.0,C
37,Austin Reaves,LAL,28.0,51,34.5,7.3,14.9,0.490,2.3,6.4,0.360,6.3,7.3,0.871,0.6,4.1,4.7,5.5,3.0,1.1,0.4,2.2,23.3,2026,46.0,"PG,SF,SG"
144,Derrick White,BOS,31.0,77,34.1,5.7,14.4,0.394,2.7,8.3,0.327,2.4,2.6,0.902,1.1,3.3,4.4,5.4,1.7,1.1,1.3,1.5,16.5,2026,47.0,"PG,SG"
301,Josh Hart,NYK,31.0,66,30.2,4.6,9.0,0.508,1.5,3.7,0.413,1.4,1.9,0.720,1.4,6.0,7.4,4.8,1.9,1.1,0.3,2.5,12.0,2026,48.0,"SF,SG"
169,Dyson Daniels,ATL,23.0,76,33.2,5.3,10.2,0.517,0.3,1.5,0.188,1.0,1.6,0.615,2.4,4.4,6.8,5.9,1.8,2.0,0.4,2.2,11.9,2026,49.0,"PG,SF,SG"
98,Coby White,CHA,26.0,50,25.0,5.6,12.5,0.446,2.3,6.4,0.362,3.9,4.8,0.817,0.3,3.1,3.4,4.0,2.6,0.5,0.1,2.2,17.4,2026,50.0,"PG,SG"
399,Michael Porter Jr.,BKN,28.0,52,32.5,8.5,18.4,0.463,3.4,9.3,0.363,3.8,4.4,0.859,1.3,5.7,7.1,3.0,2.3,1.1,0.3,2.2,24.2,2026,51.0,"SF,PF"
139,Deni Avdija,POR,25.0,66,33.3,7.5,16.1,0.462,1.9,6.0,0.318,7.4,9.2,0.802,1.1,5.8,6.9,6.7,3.8,0.8,0.6,2.5,24.2,2026,52.0,"PF,SF,SG"
253,Jarrett Allen,CLE,28.0,56,27.1,6.0,9.4,0.638,0.0,0.2,0.100,3.3,4.7,0.709,2.6,5.9,8.5,1.8,1.3,1.0,0.8,1.7,15.4,2026,53.0,C
232,Jalen Duren,DET,22.0,70,28.2,7.5,11.5,0.650,0.0,0.0,0.000,4.6,6.1,0.747,3.8,6.7,10.5,2.0,1.9,0.8,0.8,2.8,19.5,2026,54.0,C
400,Mikal Bridges,NYK,29.0,82,32.8,5.8,11.7,0.490,1.9,5.1,0.371,1.0,1.2,0.827,1.0,2.8,3.8,3.7,1.0,1.3,0.8,2.0,14.4,2026,56.0,"PF,SF,SG"
440,OG Anunoby,NYK,28.0,67,33.2,5.8,12.0,0.484,2.3,6.1,0.386,2.7,3.3,0.828,1.3,4.0,5.2,2.2,1.8,1.6,0.7,2.4,16.7,2026,57.0,"SF,PF"
415,Myles Turner,MIL,30.0,71,26.9,4.0,9.1,0.440,2.1,5.4,0.383,1.8,2.5,0.740,1.1,4.3,5.3,1.5,1.2,0.7,1.6,2.6,11.9,2026,60.0,C
510,Stephon Castle,SAS,21.0,68,30.0,5.7,12.0,0.471,1.2,3.6,0.332,4.1,5.6,0.734,1.4,3.9,5.3,7.4,3.2,1.1,0.3,3.3,16.7,2026,62.0,"PG,SG"
275,Jimmy Butler III,GSW,36.0,38,31.1,6.3,12.2,0.519,0.8,2.2,0.376,6.5,7.6,0.864,2.3,3.2,5.6,4.9,1.6,1.4,0.2,1.2,20.0,2026,67.0,"PF,SF,SG"
483,Rudy Gobert,MIN,34.0,76,31.3,4.4,6.5,0.682,0.0,0.1,0.000,2.1,4.0,0.526,3.9,7.5,11.5,1.7,1.4,0.8,1.6,2.6,10.9,2026,70.0,C
577,Zach LaVine,SAC,31.0,39,31.4,6.7,14.0,0.479,2.5,6.5,0.390,3.2,3.6,0.880,0.2,2.6,2.8,2.3,1.9,0.7,0.3,2.1,19.2,2026,72.0,"PG,SF,SG"
125,Darius Garland,LAC,26.0,45,29.9,6.9,14.9,0.460,2.7,6.8,0.396,2.3,2.7,0.861,0.4,2.0,2.4,6.7,2.9,1.0,0.2,1.9,18.8,2026,73.0,PG
348,Kon Knueppel,CHA,20.0,81,31.5,6.4,13.4,0.475,3.4,7.9,0.425,2.4,2.8,0.863,1.2,4.1,5.3,3.4,2.0,0.7,0.2,2.1,18.5,2026,74.0,"SF,SG"
230,Jakob Poeltl,TOR,30.0,46,25.0,4.7,6.7,0.700,0.0,0.0,0.000,1.3,2.1,0.602,2.5,4.5,7.0,2.0,1.2,0.9,0.7,3.2,10.7,2026,76.0,C
27,Andrew Wiggins,MIA,31.0,68,30.3,5.7,12.1,0.475,2.0,4.9,0.414,1.9,2.4,0.784,1.7,3.1,4.8,2.7,1.5,1.1,1.0,2.3,15.4,2026,77.0,"PF,SF,SG"
446,Onyeka Okongwu,ATL,25.0,74,31.0,5.6,11.6,0.480,1.9,5.2,0.376,2.1,2.7,0.757,1.9,5.7,7.6,3.1,1.7,1.1,1.1,3.3,15.2,2026,78.0,C
337,Kevin Porter Jr.,MIL,26.0,38,33.2,6.3,13.5,0.465,1.2,3.8,0.322,3.6,4.1,0.878,0.9,4.3,5.2,7.4,2.9,2.2,0.5,2.3,17.4,2026,79.0,"PG,SG"
16,Alex Sarr,WAS,21.0,48,27.2,6.6,13.7,0.482,1.0,3.1,0.333,2.1,3.0,0.692,2.2,5.2,7.4,2.7,1.7,0.8,2.0,2.2,16.3,2026,80.0,"C,PF"
223,Jaden McDaniels,MIN,25.0,73,31.7,5.7,11.1,0.515,1.4,3.4,0.412,2.0,2.4,0.835,1.0,3.2,4.2,2.7,1.8,1.1,1.0,3.3,14.8,2026,82.0,"PF,SF"
94,Christian Braun,DEN,25.0,44,31.8,4.6,8.8,0.519,1.0,3.3,0.301,1.8,2.3,0.782,1.4,3.4,4.8,2.7,1.0,0.7,0.3,2.3,12.0,2026,83.0,"PF,SF,SG"
70,CJ McCollum,ATL,34.0,76,29.8,6.9,15.2,0.455,2.5,6.7,0.375,2.4,3.1,0.772,0.8,2.5,3.3,3.9,1.8,0.8,0.5,1.9,18.7,2026,84.0,"PG,SG"
471,RJ Barrett,TOR,26.0,57,30.3,7.0,14.3,0.491,1.7,5.0,0.339,3.5,4.9,0.717,1.0,4.3,5.3,3.3,1.7,0.7,0.3,2.6,19.3,2026,87.0,"PF,SF,SG"
462,Payton Pritchard,BOS,28.0,79,32.3,6.4,13.8,0.464,2.7,7.1,0.377,1.5,1.7,0.890,0.9,3.1,3.9,5.2,1.4,0.7,0.1,1.5,17.0,2026,89.0,"PG,SG"
475,Reed Sheppard,HOU,22.0,82,26.2,5.0,11.5,0.430,2.8,7.0,0.394,0.8,1.0,0.802,0.3,2.6,2.9,3.4,1.5,1.5,0.7,2.0,13.5,2026,91.0,"PG,SG"
168,Dylan Harper,SAS,20.0,69,22.6,4.8,9.5,0.505,0.9,2.6,0.343,1.3,1.7,0.756,0.8,2.6,3.4,3.9,1.4,0.8,0.3,2.0,11.8,2026,92.0,"PG,SG"
58,Brandon Miller,CHA,23.0,65,30.3,7.0,16.1,0.435,3.1,8.2,0.383,3.1,3.4,0.892,1.1,3.8,4.9,3.3,2.5,1.0,0.7,2.8,20.2,2026,93.0,"PF,SF,SG"
153,Donovan Clingan,POR,22.0,77,27.2,4.6,8.9,0.520,1.1,3.2,0.341,1.8,2.6,0.680,4.5,7.1,11.6,2.1,1.2,0.6,1.7,2.4,12.1,2026,96.0,C
26,Andrew Nembhard,IND,26.0,57,31.3,5.8,13.2,0.442,1.9,5.2,0.361,3.4,4.1,0.825,0.4,2.4,2.8,7.7,2.4,0.9,0.1,2.2,16.9,2026,97.0,"PG,SG"
36,Ausar Thompson,DET,23.0,73,26.0,4.2,7.9,0.525,0.1,0.3,0.250,1.5,2.6,0.571,2.1,3.7,5.7,3.1,1.5,2.0,0.9,2.7,9.9,2026,98.0,"PF,SF,SG"
558,VJ Edgecombe,PHI,20.0,75,35.0,6.0,13.7,0.438,2.0,5.6,0.354,2.0,2.4,0.818,1.6,4.0,5.6,4.2,1.8,1.4,0.5,2.9,16.0,2026,99.0,"PG,SG"
426,Nickeil Alexander-Walker,ATL,27.0,78,33.4,7.0,15.3,0.459,3.2,8.1,0.399,3.6,3.9,0.902,0.7,2.8,3.4,3.7,2.1,1.3,0.5,2.2,20.8,2026,102.0,"PG,SG"
513,T.J. McConnell,IND,34.0,56,17.2,4.3,8.0,0.538,0.3,0.9,0.320,0.4,0.5,0.862,0.4,1.8,2.2,5.1,1.1,1.0,0.2,1.1,9.4,2026,105.0,PG
159,Draymond Green,GSW,36.0,68,27.5,3.0,7.2,0.418,1.5,4.6,0.326,0.9,1.2,0.702,0.8,4.7,5.5,5.5,2.7,0.9,0.6,2.9,8.4,2026,106.0,"PF,C"
500,Shaedon Sharpe,POR,23.0,50,29.4,7.8,17.4,0.452,2.1,6.1,0.337,3.1,3.9,0.787,1.0,3.3,4.3,2.6,2.9,1.4,0.1,2.0,20.8,2026,108.0,"PG,SF,SG"
381,Malik Monk,SAC,28.0,62,22.0,4.5,10.2,0.438,2.0,5.1,0.395,1.5,1.7,0.879,0.2,1.6,1.9,3.0,1.5,0.6,0.4,1.6,12.5,2026,110.0,"PG,SG"
203,Immanuel Quickley,TOR,27.0,70,31.9,5.7,12.9,0.443,2.5,6.8,0.374,2.4,3.0,0.821,0.5,3.5,4.0,5.9,1.5,1.3,0.1,2.0,16.4,2026,111.0,"PG,SG"
208,Isaiah Hartenstein,OKC,28.0,47,24.2,3.9,6.3,0.622,0.0,0.1,0.000,1.4,2.2,0.610,3.2,6.3,9.4,3.5,1.7,1.0,0.8,2.5,9.2,2026,112.0,C
3,Aaron Gordon,DEN,30.0,36,27.9,5.5,11.1,0.497,1.7,4.4,0.389,3.5,4.5,0.767,1.4,4.4,5.8,2.7,1.1,0.6,0.3,1.7,16.2,2026,113.0,"PF,C"
390,Matas Buzelis,CHI,21.0,77,29.2,5.8,12.5,0.463,2.2,6.4,0.349,2.4,3.1,0.786,1.0,4.8,5.8,2.1,2.1,0.7,1.5,2.3,16.3,2026,115.0,"SF,PF"
489,Ryan Rollins,MIL,23.0,74,32.1,6.6,13.9,0.472,2.5,6.1,0.406,1.7,2.1,0.796,0.7,3.8,4.6,5.6,2.7,1.5,0.4,2.6,17.3,2026,116.0,"PG,SG"
148,Devin Vassell,SAS,25.0,67,30.5,4.9,11.3,0.437,2.5,6.4,0.384,1.6,1.9,0.815,0.6,3.4,4.0,2.5,0.9,0.9,0.4,1.6,13.9,2026,119.0,"SG,SF"
576,Zach Edey,MEM,24.0,11,25.8,5.6,8.9,0.633,0.1,0.5,0.200,2.3,2.9,0.781,3.9,7.2,11.1,1.1,2.4,0.6,1.9,3.4,13.6,2026,122.0,C
322,Keegan Murray,SAC,25.0,23,34.5,5.5,13.0,0.420,1.3,4.9,0.277,1.7,2.1,0.776,1.4,4.3,5.7,1.7,1.2,1.0,1.6,1.8,14.0,2026,123.0,"SF,PF"
547,Ty Jerome,MEM,28.0,15,22.6,6.8,14.3,0.474,2.8,6.7,0.420,3.3,3.7,0.875,0.7,2.1,2.8,5.7,1.8,1.1,0.3,2.1,19.7,2026,128.0,"PG,SG"
218,Jabari Smith Jr.,HOU,23.0,77,35.1,5.7,12.7,0.449,2.3,6.3,0.363,2.1,2.7,0.775,1.4,5.5,6.9,1.9,1.4,0.7,0.9,2.5,15.8,2026,129.0,"C,PF"
119,Daniel Gafford,DAL,27.0,55,21.7,3.8,5.7,0.655,0.0,0.0,0.000,2.0,2.9,0.683,2.5,4.4,6.9,1.1,1.1,0.8,1.3,2.6,9.5,2026,130.0,C
530,Toumani Camara,POR,26.0,82,33.3,4.8,10.9,0.440,2.7,7.2,0.370,1.2,1.7,0.708,1.6,3.6,5.1,2.5,1.8,1.1,0.4,2.9,13.4,2026,132.0,"PF,SF"
238,Jalen Suggs,ORL,25.0,57,27.6,4.9,11.4,0.435,2.1,6.3,0.339,1.8,2.1,0.855,0.6,3.2,3.9,5.5,2.7,1.8,0.7,2.5,13.8,2026,135.0,"PG,SG"
250,Jared McCain,OKC,22.0,67,17.3,3.0,7.2,0.425,1.5,3.8,0.385,0.8,0.9,0.864,0.3,1.7,2.0,1.3,0.8,0.5,0.1,1.2,8.3,2026,137.0,"PG,SG"
305,Jrue Holiday,POR,36.0,53,29.4,6.0,13.4,0.451,2.6,6.8,0.378,1.7,2.0,0.838,1.3,3.3,4.6,6.1,2.8,1.0,0.1,1.5,16.3,2026,140.0,"PG,SG"
516,Tari Eason,HOU,25.0,60,25.8,4.0,9.7,0.416,1.6,4.3,0.358,0.9,1.1,0.776,2.1,4.2,6.3,1.5,1.4,1.2,0.5,2.3,10.5,2026,142.0,"PF,SF,SG"
356,Kyshawn George,WAS,22.0,48,29.0,5.3,12.0,0.438,2.1,5.4,0.381,2.2,2.7,0.802,0.9,4.2,5.1,4.5,2.6,1.0,0.9,3.5,14.8,2026,145.0,"PF,SF,SG"
155,Donte DiVincenzo,MIN,29.0,82,30.4,4.1,10.2,0.406,3.0,7.9,0.379,1.0,1.3,0.743,0.8,3.3,4.1,3.8,1.4,1.3,0.4,2.4,12.2,2026,146.0,"PG,SF,SG"
422,Neemias Queta,BOS,26.0,76,25.3,4.3,6.6,0.653,0.0,0.1,0.125,1.6,2.3,0.703,3.0,5.3,8.4,1.7,1.0,0.8,1.3,2.8,10.2,2026,147.0,C
495,Scoot Henderson,POR,22.0,30,24.9,4.8,11.4,0.418,1.9,5.4,0.352,2.8,3.3,0.840,0.6,2.1,2.7,3.7,2.4,0.9,0.3,2.8,14.2,2026,148.0,"PG,SG"
29,Anthony Black,ORL,22.0,64,29.8,5.4,12.1,0.447,1.6,4.7,0.333,2.6,3.6,0.732,0.7,3.1,3.8,3.7,2.1,1.4,0.7,2.7,15.0,2026,149.0,"PG,SG,SF"
55,Brandin Podziemski,GSW,23.0,82,28.4,4.8,10.6,0.455,1.9,5.0,0.371,2.3,2.9,0.797,0.9,4.2,5.1,3.7,1.6,1.1,0.2,1.7,13.8,2026,151.0,"PG,SG"
38,Ayo Dosunmu,MIN,26.0,69,27.3,5.6,10.8,0.517,1.8,4.1,0.439,1.8,2.1,0.876,0.7,2.8,3.4,3.6,1.4,0.8,0.3,1.9,14.8,2026,154.0,"PG,SF,SG"
83,Cason Wallace,OKC,22.0,77,26.6,3.3,7.6,0.432,1.3,3.7,0.351,0.7,0.9,0.809,0.8,2.3,3.1,2.6,0.9,1.9,0.4,2.0,8.6,2026,155.0,"PG,SF,SG"
61,Bronny James,LAL,21.0,42,8.9,1.1,2.7,0.409,0.5,1.4,0.386,0.1,0.2,0.857,0.1,0.4,0.5,1.2,0.6,0.5,0.1,0.7,2.9,2026,156.0,"PG,SG"
497,Scotty Pippen Jr.,MEM,25.0,10,21.2,4.3,9.6,0.448,1.0,3.2,0.313,1.8,2.3,0.783,0.8,1.4,2.2,4.7,2.7,1.9,0.4,3.1,11.4,2026,159.0,"PG,SG"
14,Alex Caruso,OKC,32.0,56,18.2,2.3,5.4,0.423,0.9,3.2,0.293,0.7,0.9,0.804,0.5,2.3,2.8,2.0,0.9,1.3,0.3,1.2,6.2,2026,162.0,"PG,SG,SF"
306,Julian Champagnie,SAS,25.0,82,27.6,3.7,8.4,0.437,2.4,6.2,0.381,1.4,1.6,0.844,0.9,4.9,5.8,1.5,0.8,0.8,0.5,1.6,11.1,2026,163.0,"PF,SF,SG"
441,Obi Toppin,IND,28.0,24,17.7,4.2,8.3,0.503,1.5,4.4,0.352,1.8,1.9,0.913,0.5,3.9,4.4,2.3,1.2,0.5,0.0,1.2,11.6,2026,165.0,"PF,SF"
354,Kyle Kuzma,MIL,30.0,69,26.2,4.9,10.0,0.492,1.2,3.5,0.347,2.0,2.7,0.726,0.8,3.7,4.5,2.7,1.7,0.7,0.4,1.9,13.0,2026,172.0,"SF,PF"
298,Jose Alvarado,NYK,28.0,69,19.9,2.7,6.5,0.416,1.5,4.2,0.352,0.5,0.7,0.761,0.4,2.1,2.5,3.4,1.1,1.0,0.1,1.9,7.4,2026,179.0,PG
105,Collin Murray-Boyles,TOR,21.0,57,21.9,3.5,6.0,0.579,0.3,0.9,0.340,1.2,1.9,0.657,2.3,2.7,5.0,1.9,1.0,0.9,0.9,2.6,8.5,2026,180.0,"C,PF"
128,Davion Mitchell,MIA,27.0,70,28.6,3.7,7.6,0.490,1.3,3.3,0.395,0.6,0.9,0.646,0.5,2.2,2.7,6.5,1.5,1.0,0.2,2.6,9.3,2026,185.0,PG
79,Cameron Johnson,DEN,30.0,54,30.5,4.2,8.8,0.480,2.0,4.7,0.430,1.7,2.1,0.839,0.8,3.0,3.8,2.4,0.9,0.7,0.4,2.3,12.2,2026,186.0,"PF,SF"
291,Jordan Clarkson,NYK,34.0,72,17.8,3.3,7.3,0.451,1.0,3.0,0.327,1.1,1.3,0.830,0.9,0.9,1.8,1.3,0.9,0.4,0.1,1.7,8.6,2026,192.0,"PG,SF,SG"
263,Jaylin Williams,OKC,24.0,65,19.7,2.3,5.4,0.423,1.5,3.9,0.383,1.1,1.4,0.793,0.5,5.0,5.5,2.4,1.0,0.5,0.6,2.0,7.2,2026,193.0,"PF,C"
12,Al Horford,GSW,40.0,45,21.5,3.1,7.2,0.426,1.6,4.6,0.361,0.5,0.6,0.846,1.0,3.9,4.9,2.6,0.9,0.7,1.1,1.1,8.3,2026,196.0,"PF,C"
82,Carter Bryant,SAS,20.0,71,11.5,1.5,3.7,0.408,0.7,2.2,0.335,0.4,0.6,0.714,0.5,2.0,2.5,0.7,0.5,0.2,0.3,1.3,4.2,2026,197.0,"PF,SF"
375,Luke Kornet,SAS,30.0,68,21.0,2.6,4.0,0.643,0.0,0.0,0.000,1.4,1.7,0.825,2.7,3.4,6.1,1.9,0.4,0.5,1.0,1.8,6.5,2026,200.0,C
0,A.J. Lawson,TOR,25.0,24,9.4,1.4,3.3,0.436,0.8,1.9,0.422,0.6,0.8,0.778,0.4,1.4,1.8,0.3,0.3,0.5,0.2,1.1,4.2,2026,NaN,NaN
1,AJ Green,MIL,26.0,78,29.1,3.4,7.9,0.424,3.0,7.1,0.419,0.7,0.8,0.855,0.4,2.4,2.7,1.9,1.0,0.5,0.1,2.3,10.4,2026,NaN,NaN
2,AJ Johnson,DAL,21.0,48,9.4,1.2,3.7,0.324,0.3,1.2,0.211,0.7,0.8,0.850,0.3,0.9,1.1,1.0,0.6,0.2,0.1,0.6,3.3,2026,NaN,NaN
4,Aaron Holiday,HOU,29.0,57,13.7,1.8,4.4,0.417,1.2,3.0,0.394,0.6,0.7,0.854,0.2,0.8,1.0,1.1,0.7,0.5,0.1,1.3,5.5,2026,NaN,NaN
5,Aaron Nesmith,IND,26.0,45,29.7,4.7,11.4,0.414,2.3,6.2,0.379,2.0,2.5,0.829,1.1,3.1,4.2,1.9,1.4,0.6,0.5,2.8,13.8,2026,NaN,NaN
6,Aaron Wiggins,OKC,27.0,65,21.8,3.6,8.2,0.431,1.5,4.2,0.356,0.8,1.1,0.736,0.6,2.4,3.1,1.7,1.2,0.9,0.4,1.3,9.4,2026,NaN,NaN
7,Ace Bailey,UTA,19.0,72,27.6,5.5,12.4,0.443,1.9,5.5,0.344,0.9,1.2,0.750,1.4,2.8,4.2,1.8,1.5,0.8,0.7,2.7,13.8,2026,NaN,NaN
8,Adama Bal,MEM,22.0,8,30.2,3.5,8.5,0.412,2.3,5.5,0.409,1.1,1.3,0.900,0.8,2.4,3.1,2.4,0.8,1.1,0.1,3.4,10.4,2026,NaN,NaN
9,Adem Bona,PHI,23.0,71,17.4,1.8,3.1,0.595,0.0,0.1,0.333,1.1,1.6,0.708,1.8,2.5,4.3,0.5,0.8,0.4,1.2,2.2,4.8,2026,NaN,NaN
10,Adou Thiero,LAL,22.0,25,6.0,0.6,1.2,0.516,0.0,0.1,0.333,0.6,0.9,0.636,0.4,0.8,1.1,0.4,0.4,0.3,0.1,0.8,1.9,2026,NaN,NaN
11,Ajay Mitchell,OKC,24.0,57,25.8,5.0,10.4,0.485,1.1,3.1,0.347,2.5,2.8,0.870,0.7,2.6,3.3,3.6,1.4,1.2,0.3,2.1,13.6,2026,NaN,NaN
13,Alex Antetokounmpo,MIL,24.0,6,3.4,0.5,1.3,0.375,0.3,1.2,0.286,1.8,2.5,0.733,0.3,0.7,1.0,0.2,0.2,0.0,0.2,0.2,3.2,2026,NaN,NaN
15,Alex Morales,ORL,28.0,4,5.9,0.8,1.8,0.429,0.0,0.3,0.000,0.5,0.5,1.000,0.3,0.5,0.8,1.0,1.0,0.0,0.0,1.8,2.0,2026,NaN,NaN
17,Alijah Martin,TOR,24.0,23,6.3,0.7,2.2,0.320,0.2,0.9,0.190,0.7,0.8,0.789,0.4,0.5,0.9,0.5,0.3,0.3,0.2,0.5,2.2,2026,NaN,NaN
18,Alondes Williams,WAS,27.0,4,25.2,4.0,6.5,0.615,1.3,3.5,0.357,1.8,2.0,0.875,1.3,5.0,6.3,3.0,1.3,0.8,0.8,1.0,11.0,2026,NaN,NaN
20,Amari Williams,BOS,24.0,22,6.6,0.5,0.9,0.500,0.0,0.0,0.000,0.5,0.6,0.714,0.4,1.4,1.8,0.5,0.5,0.1,0.5,0.9,1.4,2026,NaN,NaN
22,Amir Coffey,PHX,29.0,46,10.7,1.2,2.5,0.487,0.4,1.1,0.347,0.5,0.6,0.786,0.4,0.8,1.2,0.6,0.2,0.2,0.1,0.7,3.2,2026,NaN,NaN
23,Andersson Garcia,UTA,25.0,5,33.8,1.8,5.8,0.310,0.2,2.6,0.077,1.4,1.8,0.778,3.4,5.0,8.4,2.8,1.4,1.6,0.8,3.2,5.2,2026,NaN,NaN
24,Andre Drummond,PHI,32.0,63,19.5,2.5,5.3,0.472,0.5,1.4,0.356,0.8,1.3,0.631,3.2,5.3,8.4,1.3,1.0,0.6,0.8,2.0,6.4,2026,NaN,NaN
25,Andre Jackson Jr.,MIL,24.0,48,8.5,0.8,2.5,0.328,0.3,1.3,0.250,0.4,0.7,0.625,0.5,1.0,1.5,0.9,0.6,0.4,0.1,0.9,2.4,2026,NaN,NaN
28,Anfernee Simons,CHI,27.0,55,24.9,5.2,11.8,0.440,2.7,6.9,0.385,1.3,1.4,0.896,0.6,1.9,2.5,2.4,1.2,0.5,0.1,1.7,14.3,2026,NaN,NaN
32,Anthony Gill,WAS,33.0,55,17.3,2.5,3.9,0.628,0.3,0.9,0.354,0.6,0.8,0.739,1.1,1.8,2.9,1.3,0.7,0.6,0.4,1.6,5.8,2026,NaN,NaN
33,Antonio Reeves,CHA,25.0,10,6.8,1.0,2.0,0.500,0.7,1.3,0.538,0.0,0.0,0.000,0.2,0.6,0.8,0.3,0.1,0.1,0.0,0.3,2.7,2026,NaN,NaN
34,Ariel Hukporti,NYK,24.0,54,9.2,0.8,1.5,0.563,0.0,0.1,0.250,0.5,0.6,0.788,1.0,1.9,2.9,0.5,0.6,0.2,0.5,1.2,2.2,2026,NaN,NaN
35,Asa Newell,ATL,20.0,44,11.4,2.1,3.8,0.538,0.7,1.7,0.387,0.4,0.7,0.552,1.0,1.2,2.2,0.6,0.5,0.4,0.3,1.5,5.2,2026,NaN,NaN
40,Baylor Scheierman,BOS,25.0,77,18.6,2.0,4.3,0.453,1.3,3.2,0.399,0.4,0.4,0.903,0.7,2.8,3.5,1.5,0.6,0.5,0.1,1.4,5.5,2026,NaN,NaN
41,Ben Saraf,BKN,20.0,44,20.8,2.7,6.9,0.396,0.4,2.0,0.211,1.7,2.0,0.830,0.5,1.6,2.1,3.3,2.3,0.9,0.2,1.8,7.5,2026,NaN,NaN
42,Ben Sheppard,IND,24.0,65,21.4,2.6,6.0,0.434,1.3,3.6,0.362,0.6,0.8,0.765,0.7,2.3,3.0,1.8,0.6,0.6,0.1,1.8,7.1,2026,NaN,NaN
43,Bennedict Mathurin,LAC,24.0,54,30.0,5.4,12.5,0.430,1.4,4.4,0.315,5.4,6.2,0.869,1.0,4.4,5.4,2.4,2.2,0.8,0.2,2.5,17.6,2026,NaN,NaN
44,Bez Mbeng,UTA,23.0,15,32.8,3.3,6.7,0.500,0.4,2.1,0.194,1.1,1.7,0.640,1.2,2.6,3.8,4.1,1.5,2.3,0.3,3.1,8.1,2026,NaN,NaN
45,Bilal Coulibaly,WAS,21.0,56,26.2,4.1,9.7,0.425,1.2,3.6,0.319,2.4,3.2,0.746,0.9,3.5,4.3,2.6,1.4,1.3,1.0,2.3,11.7,2026,NaN,NaN
46,Bismack Biyombo,SAS,33.0,25,5.7,0.4,0.6,0.600,0.0,0.0,0.000,0.2,0.3,0.714,0.2,0.8,1.0,0.2,0.3,0.2,0.1,1.1,0.9,2026,NaN,NaN
47,Blake Hinson,UTA,26.0,14,20.4,4.2,8.2,0.513,2.6,5.6,0.468,0.9,1.1,0.750,0.8,1.6,2.4,1.1,0.4,0.4,0.1,1.7,11.9,2026,NaN,NaN
48,Blake Wesley,POR,23.0,31,11.6,1.8,4.0,0.452,0.3,1.2,0.278,0.8,1.5,0.553,0.3,1.0,1.3,2.0,1.0,0.5,0.2,1.1,4.8,2026,NaN,NaN
49,Bobby Portis Jr.,MIL,31.0,67,24.2,5.5,11.2,0.488,2.0,4.4,0.456,0.7,1.0,0.706,1.3,5.1,6.4,1.6,1.0,0.6,0.2,1.6,13.7,2026,NaN,NaN
50,Bobi Klintman,DET,23.0,12,5.9,0.8,2.3,0.333,0.3,1.1,0.308,0.0,0.3,0.000,0.4,1.2,1.6,0.5,0.5,0.3,0.0,0.9,1.8,2026,NaN,NaN
51,Bogdan Bogdanović,LAC,33.0,23,19.7,2.6,6.6,0.388,1.4,4.1,0.347,0.9,1.1,0.800,0.3,2.3,2.6,2.2,1.2,0.4,0.1,2.0,7.4,2026,NaN,NaN
52,Bones Hyland,MIN,25.0,71,16.6,3.0,6.6,0.453,1.6,4.2,0.388,0.9,1.2,0.780,0.3,1.5,1.8,2.6,1.0,0.6,0.2,1.7,8.5,2026,NaN,NaN
53,Bradley Beal,LAC,33.0,6,20.2,3.0,8.0,0.375,1.2,3.2,0.368,1.0,1.3,0.750,0.3,0.5,0.8,1.7,1.5,0.5,0.0,2.3,8.2,2026,NaN,NaN
54,Branden Carlson,OKC,27.0,42,11.6,2.3,4.4,0.527,0.7,2.0,0.360,0.4,0.6,0.577,0.7,2.3,3.0,0.7,0.4,0.2,0.6,0.9,5.8,2026,NaN,NaN

In [10]:
df.to_csv('nba_player_averages_2026_with_adp.csv', index=False)

In [20]:
df[df["Player"].str.contains("Powell|Sarr|Davis")]

,Player,Team,Age,G,MP,FG,FGA,FG%,3P,3PA,3P%,FT,FTA,FT%,ORB,DRB,TRB,AST,TOV,STL,BLK,PF,PTS,Season,ADP,Positions
30,Anthony Davis,WAS,33.0,20,31.3,8.5,16.7,0.506,0.5,1.9,0.270,3.0,4.1,0.728,3.1,8.0,11.1,2.8,2.1,1.1,1.7,2.1,20.4,2026,9.0,"PF,C"
16,Alex Sarr,WAS,21.0,48,27.2,6.6,13.7,0.482,1.0,3.1,0.333,2.1,3.0,0.692,2.2,5.2,7.4,2.7,1.7,0.8,2.0,2.2,16.3,2026,80.0,"C,PF"
158,Drake Powell,BKN,20.0,63,20.9,2.3,5.7,0.402,0.8,2.9,0.280,1.1,1.2,0.896,0.3,1.4,1.8,1.4,1.0,0.6,0.2,1.4,6.5,2026,NaN,NaN
166,Dwight Powell,DAL,34.0,63,14.4,1.0,1.6,0.644,0.0,0.1,0.286,1.2,1.8,0.696,1.5,2.6,4.1,1.1,0.7,0.5,0.3,2.1,3.3,2026,NaN,NaN
215,JD Davison,HOU,23.0,28,7.8,0.9,2.3,0.375,0.3,1.1,0.250,0.5,0.7,0.684,0.1,1.1,1.2,1.3,0.3,0.2,0.2,0.6,2.5,2026,NaN,NaN
428,Nigel Hayes-Davis,PHX,31.0,27,7.2,0.6,1.7,0.326,0.1,0.6,0.125,0.1,0.1,0.500,0.4,0.8,1.2,0.3,0.3,0.3,0.1,0.6,1.3,2026,NaN,NaN
439,Norman Powell,MIA,33.0,58,29.6,7.3,15.4,0.470,2.7,7.1,0.380,4.5,5.5,0.827,0.4,3.1,3.5,2.5,1.9,1.1,0.2,2.2,21.7,2026,NaN,NaN
443,Olivier Sarr,CLE,27.0,4,9.8,1.3,1.8,0.714,0.5,0.8,0.667,0.5,1.3,0.400,0.5,2.3,2.8,1.3,0.5,0.5,0.8,2.3,3.5,2026,NaN,NaN
532,Trayce Jackson-Davis,TOR,26.0,53,9.4,1.3,2.3,0.573,0.0,0.0,1.000,0.7,1.4,0.514,1.2,1.5,2.7,0.7,0.4,0.3,0.5,0.8,3.4,2026,NaN,NaN